spring:
  application:
    name: Journal App
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=journal-app
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  output:
    ansi:
      enabled: ALWAYS
  main:
    allow-circular-references: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ} %highlight(%-5level) [%thread] %logger{36} - %msg%n"
  level:
    root: info
#  file:
#    name: app.log
#    path: /var/logs
server:
  port: 8080
#  servlet:
#    context-path: /journal